### ISSUE TITLE
Integrate wit `Element UI`?

### ISSUE THREAD

**Issue by thearabbit** [xaksis/vue-good-wizard#1]
I base on `Element UI`, could you example with `form validation`?

**Comment by xaksis** [comment]
hey @thearabbit, what shows up inside the wizard is controlled by you. You can add in a form with your validation mechanisms and whatever you want inside the div with the correct name. 

If you want to trigger validation when you click next, use the onNext property... which takes in a function. If validation succeeds, return true (will move wizard to next step)... or show the error message and return false (will keep the user at the current step)

Element UI's validation seems to be done asynchronously so a straight forward implementation doesn't exist for this yet.

**Comment by xaksis** [comment]
Alright I have enhanced the plugin (v 1.1.0) to allow calling for next, back asynchronously and added an example for how you can do that with element-ui form validate. cheers!
