### ISSUE TITLE
Anyway to disable final save button

### ISSUE THREAD

**Issue by kevinding0218** [xaksis/vue-good-wizard#10]
Hello, thank you for your nice step wizard and this would be by far the best and clean wizard I've seen. Well in our development we found one issue with how to disable the save button at final step. Usually there would be a post request on the save button so we would like user only click once on the button, then disable the button to prevent duplicate request send to the server, but we have no idea to attach any disable attribute to the final button, is there any suggestion or idea that you could help us?

Thank you very much!
Best

**Comment by xaksis** [comment]
Hey @kevinding0218! Glad you're liking vue-good-wizard! I'll look into providing a good way to disable next/save buttons.

**Comment by xaksis** [comment]
@kevinding0218 with v1.3.0 you can supply options with the steps to enable/disable the next button: 
```
 {
          label: 'Apply',
          slot: 'page4',
          options: {
            nextDisabled: true, // control whether next is disabled or not
          },
        }
```

**Comment by kevinding0218** [comment]
@xaksis , thank you very much for your help!!
