### ISSUE TITLE
Failed to mount component: template or render function not defined

### ISSUE THREAD

**Issue by Graahf** [xaksis/vue-good-wizard#11]
Hi,

I'm unsure, if I'm setting it up work or not, but nomatter what I do, I keep getting the **Failed to mount component**
![image](https://user-images.githubusercontent.com/1702376/42369482-658d3bf2-810a-11e8-892f-faae3c6f505b.png)

After installing it via. npm install vue-good-wizard --save

I'm importing like this:
`import VueGoodWizard from 'vue-good-wizard`;

In my script, I'm using this
![image](https://user-images.githubusercontent.com/1702376/42369436-46cb79b8-810a-11e8-9805-385ebaf7df98.png)

In my template I have this inside of some divs:
![image](https://user-images.githubusercontent.com/1702376/42369468-5ad0ad02-810a-11e8-8afd-35fde307cc8a.png)

What am I doing wrong?

// Steve

**Comment by xaksis** [comment]
hey @Graahf , documentation is a bit lacking here. I apologize for that. If you want to use VueGoodTable within a component (as opposed to importing it globally in your app), try the following: 

```js
// within your component script tag
import { GoodWizard } from 'vue-good-wizard';

// in your components
components: {
  'vue-good-wizard': GoodWizard,
}
```

Let me know if you have an issue doing above and I'll re-open. closing.
