### ISSUE TITLE
Demo link broken?

### ISSUE THREAD

**Issue by ergonomicus** [xaksis/vue-good-wizard#12]
I get 404...

**Comment by xaksis** [comment]
Hey @ergonomicus. Can you post what link are you referring to?

**Comment by ergonomicus** [comment]
https://xaksis.github.io/vue-good-demos/#/simple-wizard
The link is on the main page "vue-good-wizard Demo"...

**Comment by xaksis** [comment]
@ergonomicus ah yeah! thank you for pointing this out. The demo site has been deprecated. I have updated the demo link to point to a jsfiddle demo.

closing.
