### ISSUE TITLE
textarea overwritten by previous step

### ISSUE THREAD

**Issue by revictus** [xaksis/vue-good-wizard#16]
Replication steps (multiple steps): 

1. Start typing in the first text area
2. Hit [Next]
2. BEFORE typing in new text area, go [Back]
3. Start typing in original box. 
4. The first textarea is now also populated in the second step (which was previously empty).

It appears the first letter you type it copies over the current text to the previously empty textarea but then more typing binds to the correct step.

**Comment by xaksis** [comment]
@revictus can you create a jsfiddle to show this? I suspect this is your specific implementation rather than a vue-good-wizard issue. You can use https://jsfiddle.net/aks9800/ygkruetq/ as a base.

**Comment by revictus** [comment]
@xaksis 

Fiddle here -> http://jsfiddle.net/3847t5xm/

![vue-good-wizard-issue](https://user-images.githubusercontent.com/8649221/43680280-c651dd06-97eb-11e8-89c2-7b9ebfc477bb.gif)

In the gif you can see I populated the first text area, hit [Next] and then before typing I went [Back] and added a period. 

The entire string (now with the period) is copied to step 2. 

It is the first key press that will copy the entire string + whatever key you typed into the previously blank step. After that first keystroke the rest correctly goes back to the step you are on.

**Comment by xaksis** [comment]
@revictus thank you so much for the detailed report. This was a pesky bug to track down. Vue was doing some efficiency cache where it was using the same input even when the slots switched. This is now fixed in v1.4.1

closing. Thanks again for the extra work.

**Comment by iftekharul-dev** [comment]
if i use any image upload package when i go back its totally new . how can it works
