### ISSUE TITLE
Kitchen sink example

### ISSUE THREAD

**Issue by sirramongabriel** [xaksis/vue-good-wizard#28]
Hello, 

Awesome wizard btw! I'm having a challenge changing button text using 'finalStepLabel' from label options in your docs.

**Expected Behavior**
For the button text in the final step to change from 'save' to Update'

**Actual Behavior**
The button in the final step shows 'save' instead of 'Update'

**Steps to Reproduce the Problem**

- Applying `finalStepLabel` to options in the desired step.
- Applying `finalStepLabel` to labelOptions in the desired step.
- Applying `finalStepLabel` as its own data property.

An example:
```
data() {
  return {
      labelOptions: {
        finalStepLabel: 'Update'
      },
      steps: [
              {
                label: 'Page 1',
                slot: 'page1',
              },
              {
                label: 'Page 2',
                slot: 'page2',
              },
              {
                label: 'Page 3',
                slot: 'page3',
              },
              {
                label: 'Page 4',
                slot: 'page4',
              },
              {
                label: 'Page 5',
                slot: 'page5',
                // options: {
                //   finalStepLabel: 'Update'
                // },
                // labelOptions: {
                //   finalStepLabel: 'Update'
                // },
              },
            ],
  }
}
```

A kitchen sink example would help me determine how to utilize this feature.

**Comment by amchconsult** [comment]
I am having the same problem.
Did you figure it out?

Thank you

**Comment by amchconsult** [comment]
I go it work

```
<vue-good-wizard 
                ref="wizard"
                :steps="steps"
                :on-next="nextClicked" 
                :on-back="backClicked"
                final-step-label="Finish"
            >
...
</vue-good-wizard>
```
