### ISSUE TITLE
Uncaught ReferenceError: VueGoodWizard is not defined

### ISSUE THREAD

**Issue by kevinding0218** [xaksis/vue-good-wizard#7]
Hello, I am new to Vue2.js and I am happy to find the "VueGoodWizard" here, but I am getting this error while trying to use "VueGoodWizard" in a single html page(haven't tried in a vue project by vue-cli), this is what I've done:
abc.html
<link href="vue2-goodwizard/vue-good-wizard.css" rel="stylesheet" />
<<vue-good-wizard ...><vue-good-wizard>
<script src="vue.js"></script>
<script src="vue2-goodwizard/vue-good-wizard.js"></script>

Vue.use(VueGoodWizard);
var vmGoodWizard = new Vue(...)

Could you please help me on that? It's good when use VueGoodTable somehow but I am having trouble with this wizard control when applied in html page...

Thank you very much for your help!

Best,
Ran

**Comment by xaksis** [comment]
hey @kevinding0218, the package name you're using is wrong... 
`<script src="vue2-goodwizard/vue-good-wizard.js"></script>` it should be `vue-good-wizard` not `vue2-goodwizard`.

**Comment by kevinding0218** [comment]
Hi @xaksis , the vue2-goodwizard is just the folder name that I put "vue-good-wizard.js" and "vue-good-wizard.css" in, sorry about the confusion but you could consider it as:
-----------------------------------------------------------
<script src="./vue-good-wizard.js"></script>
<div id="app>
   <vue-good-wizard ...></vue-good-wizard>
</div>
<script>
Vue.use(VueGoodWizard);
new Vue({...})
</script>
--------------------------------------------------------
Error will contain:
Uncaught ReferenceError: VueGoodWizard is not defined at line "Vue.use(VueGoodWizard)"

The vue-good-wizard.js file is what I grabbed from "vue-good-wizard-master\dist" folder, is there something I am missing?

Best
