### ISSUE TITLE
VueGoodWizard is not defined at line "Vue.use(VueGoodWizard)"

### ISSUE THREAD

**Issue by kevinding0218** [xaksis/vue-good-wizard#8]
Hi @xaksis , I am just reopening the issue as it's closed last time. The "vue2-goodwizard" is just the folder name that I put "vue-good-wizard.js" and "vue-good-wizard.css" in, I'm sorry about the confusion but you could consider it as, I am using it in a single html page not a vue-cli project...
<script src="./vue-good-wizard.js"></script>

<script>
Vue.use(VueGoodWizard);
new Vue({...})
</script>
Error will contain:
Uncaught ReferenceError: VueGoodWizard is not defined at line "Vue.use(VueGoodWizard)"

The vue-good-wizard.js file is what I grabbed from "vue-good-wizard-master\dist" folder, is there something I am missing?

Best

**Comment by xaksis** [comment]
@kevinding0218  you don't need to do Vue.use if you're including the file as a script tag. the plugin automatically installs. refer to this jsfiddle

https://jsfiddle.net/aks9800/ygkruetq/

closing.

**Comment by kevinding0218** [comment]
Excellent catch! I am new to Vue.js and thank you very much for your help! This is Amazing!
