### ISSUE TITLE
Customize 'Save' behaivour

### ISSUE THREAD

**Issue by Erwol** [xaksis/vue-good-wizard#9]
Hello, how can we change what the 'Save' button - last step - triggers? Thanks!

**Comment by xaksis** [comment]
hey @Erwol, save is just another next call. 
```javascript 
nextClicked(currentPage) {
      console.log('next clicked', currentPage)
      return true; //return false if you want to prevent moving to next page
    },
```
you can check if the current page is your last page and if yes, do whatever you need to do for save.

**Comment by Erwol** [comment]
Awesome, thanks @xaksis
